// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.4
// source: blur.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlurService_BlurImages_FullMethodName = "/blur.BlurService/BlurImages"
)

// BlurServiceClient is the client API for BlurService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlurServiceClient interface {
	BlurImages(ctx context.Context, in *BlurImagesRequest, opts ...grpc.CallOption) (*BlurImagesResponse, error)
}

type blurServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlurServiceClient(cc grpc.ClientConnInterface) BlurServiceClient {
	return &blurServiceClient{cc}
}

func (c *blurServiceClient) BlurImages(ctx context.Context, in *BlurImagesRequest, opts ...grpc.CallOption) (*BlurImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlurImagesResponse)
	err := c.cc.Invoke(ctx, BlurService_BlurImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlurServiceServer is the server API for BlurService service.
// All implementations must embed UnimplementedBlurServiceServer
// for forward compatibility.
type BlurServiceServer interface {
	BlurImages(context.Context, *BlurImagesRequest) (*BlurImagesResponse, error)
	mustEmbedUnimplementedBlurServiceServer()
}

// UnimplementedBlurServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlurServiceServer struct{}

func (UnimplementedBlurServiceServer) BlurImages(context.Context, *BlurImagesRequest) (*BlurImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlurImages not implemented")
}
func (UnimplementedBlurServiceServer) mustEmbedUnimplementedBlurServiceServer() {}
func (UnimplementedBlurServiceServer) testEmbeddedByValue()                     {}

// UnsafeBlurServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlurServiceServer will
// result in compilation errors.
type UnsafeBlurServiceServer interface {
	mustEmbedUnimplementedBlurServiceServer()
}

func RegisterBlurServiceServer(s grpc.ServiceRegistrar, srv BlurServiceServer) {
	// If the following call pancis, it indicates UnimplementedBlurServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlurService_ServiceDesc, srv)
}

func _BlurService_BlurImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlurImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlurServiceServer).BlurImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlurService_BlurImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlurServiceServer).BlurImages(ctx, req.(*BlurImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlurService_ServiceDesc is the grpc.ServiceDesc for BlurService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlurService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blur.BlurService",
	HandlerType: (*BlurServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BlurImages",
			Handler:    _BlurService_BlurImages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blur.proto",
}
